# Generated by Django 4.2.6 on 2023-12-04 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PowerData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("contract", models.CharField(max_length=100)),
                ("auth_key", models.CharField(max_length=20)),
                ("street", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=10)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
